project: runs/train/DM-VTON_demo
name: Teacher_warp
device: '0'
dataroot: ../dataset/VITON-Clean/VITON_traindata
valroot: ../data/rail/pf
batch_size: 18
workers: 16
no_flip: false
print_step: 200
sample_step: 1000
save_period: 20
resume: false
use_dropout: false
align_corners: true
verbose: false
local_rank: -1
optimizer: Adam
niter: 50
niter_decay: 50
momentum: 0.5
lr: 5.0e-05
pb_warp_checkpoint: null
pb_gen_checkpoint: null
pf_warp_checkpoint: null
pf_gen_checkpoint: null
save_dir: runs/train/DM-VTON_demo/Teacher_warp
