debug: False
question: 'Training DM_VTON on rail data after loading it from Original VITON data'
impact: 'Low-resolution VITON for parser-free networks allowing real-time inference'
intent: 'Load the parser based warped trained on original data to pretrain the generator.' # What is the intent of the research
what_does_it_have: 'Parser Based warping trained on Original data'
rail_data: 'Contains 8 Unique Individual-Clothing Pairs'
opt_vton_yaml: 'ladi_viton.yml'

run_number: 1
experiment_number: 1
experiment_run: "experiment_{}/run_{}"
run_from_number: 1
experiment_from_number: 1
experiment_from_run: "experiment_{}/run_{}"


load_last_step: False
project: "runs/test"
device: 1
VITON_Type: "Parser_Free"
low_res_viton_dataset_name: "VITON-Clean"
VITON_Name: "DM_VTON"
VITON_selection_dir: "VITON/{}/{}"


res: "low_res"
dataset_name: "Original"
training_method: "warping"
gpu_ids: ""
batch_size: 4


try_on_fine_height: 1024
datamode: "train"
VITON_Model: "PB_Warp"
rail_dir: "data/VITON/{}/processed/{}/{}"
original_dir: "data/VITON/{}/processed/{}/{}"
root_dir: "/home-mscluster/mmolefe/Playground/Synthesising Virtual Fashion Try-On with Neural Radiance Fields/Fashion-SuperNeRF"
model_dir: "VITON/Parser_Free/DM_VTON/{}"
dataroot: "../data/VITON-Clean"
valroot: "../data/VITON-Clean"

tensorboard_dir: "./tensorboard/{}/{}"
results_dir: "./results/{}/{}"

# TPS
tps_save_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
tps_save_step_checkpoint: "tps_%06d.pt"
tps_load_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
tps_load_step_checkpoint: "tps_%06d.pt"

tps_save_final_checkpoint_dir: "./checkpoints/{}/{}"
tps_save_final_checkpoint: "tps.pt"
tps_load_final_checkpoint_dir: "./checkpoints/{}/{}"
tps_load_final_checkpoint: "tps.pt"

# VTO
vto_save_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
vto_save_step_checkpoint: "vto_%06d.pt"
vto_load_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
vto_load_step_checkpoint: "vto_%06d.pt"

vto_save_final_checkpoint_dir: "./checkpoints/{}/{}"
vto_save_final_checkpoint: "vto.pt"
vto_load_final_checkpoint_dir: "./checkpoints/{}/{}"
vto_load_final_checkpoint: "vto.pt"

# Emasc
emasc_save_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
emasc_save_step_checkpoint: "emasc_%06d.pt"
emasc_load_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
emasc_load_step_checkpoint: "emasc_%06d.pt"

emasc_save_final_checkpoint_dir: "./checkpoints/{}/{}"
emasc_save_final_checkpoint: "emasc.pt"
emasc_load_final_checkpoint_dir: "./checkpoints/{}/{}"
emasc_load_final_checkpoint: "emasc.pt"

# inversion
inversion_save_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
inversion_save_step_checkpoint: "inversion_%06d.pt"
inversion_load_step_checkpoint_dir: "./checkpoints/{}/{}/steps"
inversion_load_step_checkpoint: "inversion_%06d.pt"

inversion_save_final_checkpoint_dir: "./checkpoints/{}/{}"
inversion_save_final_checkpoint: "inversion.pt"
inversion_load_final_checkpoint_dir: "./checkpoints/{}/{}"
inversion_load_final_checkpoint: "inversion.pt"




resume: false
use_dropout: false
align_corners: false
verbose: false
local_rank: -1
optimizer: "Adam"
momentum: 0.5
epsilon: 0.001
lr: 0.00005

tps_checkpoint: ""
tps_discriminator_checkpoint: ""
wandb_name: wandb_name
tps_load_from_model: Original
tps_discriminator_load_from_model: Rail

batch_size: 4
cuda: true
datamode: train
dataroot: ../data/VITON-Clean
dataset_name: Original
experiment_from_number: 1
experiment_from_run: experiment_{}/run_{}
experiment_number: 1
experiment_run: experiment_{}/run_{}
gpu_ids: ''
local_rank: -1
low_res_viton_dataset_name: VITON-Clean
lr: 5.0e-05
model_dir: VITON/Parser_Free/DM_VTON/{}
momentum: 0.5
optimizer: Adam
original_dir: data/VITON/{}/processed/{}/{}



# Recordable Hyperparameters
# General Hyperparameters
niter: 50 # opt.niter + opt.niter_decay = total number of epochs
niter_decay: 50
display_count: 1 # Frequency Of Saving Training Results As Images & Graphs
print_step: 1 # Frequency Of Print Training Results On Screen'
save_period: 1 # Frequency Of Saving Checkpoints At The End Of Epochs
viton_batch_size: 4
run_wandb: True
continue_train: False
val_count: 1
const_weight: 0.01
dense: False
only_extraction: False
vgg_weight: 0.25
l1_weight: 1
save_path: None
epochs_tps: 50
epochs_refinement: 50
dataset: 'vitonhd'
height: 512
width: 384
viton_workers: 1
pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-inpainting"
seed: 1234
train_batch_size: 16
test_batch_size: 16
num_train_epochs: 100
max_train_steps: 40001
gradient_accumulation_steps: 1
learning_rate: 0.00001
lr_scheduler: "constant_with_warmup"
lr_warmup_steps: 500
allow_tf32: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-08
max_grad_norm: 1.0
mixed_precision: "fp16"
report_to: "wandb"
local_rank: -1
checkpointing_steps: 10000
resume_from_checkpoint: False
num_workers: 8
num_workers_test: 8
test_order: "paired"
emasc_type: "nonlinear"
emasc_kernel: 3
emasc_padding: 1
