debug: 0
sweeps: 0
run_wandb: 0

# ========================= Training intention
question: 'Training CP_VTON on Original data'
impact: 'Low-resolution VITON for parser-based networks'
intent: 'Load the parser based warped trained on original data to pretrain the generator.' # What is the intent of the research
what_does_it_have: 'Parser Based warping trained on Original data'
rail_data: 'Contains 8 Unique Individual-Clothing Pairs'


# ========================= Run Hyperparameters
run_number: 1
experiment_number: 1
experiment_run: "experiment_{}/run_{}"
run_from_number: 1
experiment_from_number: 1
experiment_from_run: "experiment_{}/run_{}"

# ========================= Machine Hyperparameters
res: "low_res"
load_last_step: False
resize_or_crop: scale_width
device: 1
gpu_ids: ""
VITON_Model: ""
wandb_name: wandb_name
cuda: true
viton_batch_size: 1
viton_workers: 1
batchSize: 1
run_wandb: true




# ========================= VITON dataset
dataset_name: "Original"
low_res_viton_dataset_name: "viton_plus"
dataroot: ../data/CP_VTON
fine_width: 192
fine_height: 256


# ========================= VITON information
VITON_Name: "CP_VTON"
VITON_Type: "Parser_Free"
datamode: "train"



# ========================= Directory
VITON_selection_dir: "VITON/{}/{}"
rail_dir: "data/VITON/{}/processed/{}/{}"
original_dir: "data/VITON/{}/processed/{}/{}"
#root_dir: "/home-mscluster/mmolefe/Playground/Synthesising Virtual Fashion Try-On with Neural Radiance Fields/Fashion-SuperNeRF"
root_dir: '/mnt/data/home/molefe/Playground/Synthesising Virtual Fashion Try-On with Neural Radiance Fields/Fashion-NeRF'
checkpoint_root_dir: "/gluster/mmolefe"
dataset_root_dir: "/datasets/mmolefe"
model_dir: "VITON/Parser_Free/CP_VTON/{}"
dataroot: "../data/CP_VTON"
valroot: "../data/CP_VTON"
tensorboard_dir: "./tensorboard/{}/{}"
results_dir: "./results/{}/{}"

# ================================= GMM ================================= 
gmm_save_step_checkpoint_dir: "/checkpoints/{}/{}/steps"
gmm_save_step_checkpoint: "gmm_step_%06d.pth"
gmm_load_step_checkpoint_dir: "/checkpoints/{}/{}/steps"
gmm_load_step_checkpoint: "gmm_step_%06d.pth"

gmm_save_final_checkpoint_dir: "/checkpoints/{}/{}"
gmm_save_final_checkpoint: "gmm_final.pth"
gmm_load_final_checkpoint_dir: "/checkpoints/{}/{}"
gmm_load_final_checkpoint: "gmm_final.pth"


# ================================= TOM ================================= 
tom_save_step_checkpoint_dir: "/checkpoints/{}/{}/steps"
tom_save_step_checkpoint: "tom_step_%06d.pth"
tom_load_step_checkpoint_dir: "/checkpoints/{}/{}/steps"
tom_load_step_checkpoint: "tom_step_%06d.pth"

tom_save_final_checkpoint_dir: "/checkpoints/{}/{}"
tom_save_final_checkpoint: "tom_final.pth"
tom_load_final_checkpoint_dir: "/checkpoints/{}/{}"
tom_load_final_checkpoint: "tom_final.pth"



# ===================== Input/Output Hyperparameters
input_nc: 3
output_nc: 3


# ===================== Experiment Hyperparameters
niter: 100000 # opt.niter + opt.niter_decay = total number of epochs
niter_decay: 100000
val_count: 20
load_step: 0
VITON_Model: GMM
stage: GMM
shuffle: True
seed: 1
segment_anything: False
# =====================  Sweep Hyperparameters
lr: 0.0001
radius: 5
grid_size: 5

# ===================== Logging Hyperparameters
display_count: 20 # Frequency Of Saving Training Results As Images & Graphs
print_step: 20 # Frequency Of Print Training Results On Screen'
save_period: 100 # Frequency Of Saving Checkpoints At The End Of Epochs